name: HDL Buspro Bridge
version: "1.0.6"
slug: hdl_buspro
description: HDL Buspro Cloud to MQTT bridge for Home Assistant
startup: services
boot: auto
init: false

arch:
  - amd64
  - aarch64
  - armv7

options:
  hdl_user: ""
  hdl_pass: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  poll_interval: 5
  home_names: []

schema:
  hdl_user: str
  hdl_pass: password
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_pass: password?
  poll_interval: int
  home_names: [str]

