name: HDL Buspro Bridge
version: "1.2"
slug: hdl_buspro
description: HDL Buspro to MQTT bridge for Home Assistant
startup: services
boot: auto
init: false

arch:
  - amd64
  - aarch64
  - armv7

options:
  hdl_user: ""
  hdl_pass: ""
  hdl_server: "ru"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  poll_interval: 5
  home_names: ""

schema:
  hdl_user: str
  hdl_pass: str
  hdl_server: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_pass: str?
  poll_interval: int
  home_names: str